package com.model;

import java.util.Date;

/**
 * TShiti generated by MyEclipse Persistence Tools
 */

public class TShiti implements java.io.Serializable
{

	// Fields

	private Integer shitiId;

	private String shitiName;

	private String shitiFujian;

	private String shitiFujianleixing;

	private String shitiFujianyuanshiming;

	private String shitiFaburiqi;

	private String shitiFabuzhe;

	private String shitiType;//管理员发布的试题和学生上传给老师的试题

	private String shitiOne1;

	private String shitiOne2;

	private String shitiOne3;

	private String shitiOne4;

	private Date shitiOne5;

	private Date shitiOne6;

	private Integer shitiOne7;

	private Integer shitiOne8;

	// Constructors

	/** default constructor */
	public TShiti()
	{
	}

	/** full constructor */
	public TShiti(String shitiName, String shitiFujian,
			String shitiFujianleixing, String shitiFujianyuanshiming,
			String shitiFaburiqi, String shitiFabuzhe, String shitiType,
			String shitiOne1, String shitiOne2, String shitiOne3,
			String shitiOne4, Date shitiOne5, Date shitiOne6,
			Integer shitiOne7, Integer shitiOne8)
	{
		this.shitiName = shitiName;
		this.shitiFujian = shitiFujian;
		this.shitiFujianleixing = shitiFujianleixing;
		this.shitiFujianyuanshiming = shitiFujianyuanshiming;
		this.shitiFaburiqi = shitiFaburiqi;
		this.shitiFabuzhe = shitiFabuzhe;
		this.shitiType = shitiType;
		this.shitiOne1 = shitiOne1;
		this.shitiOne2 = shitiOne2;
		this.shitiOne3 = shitiOne3;
		this.shitiOne4 = shitiOne4;
		this.shitiOne5 = shitiOne5;
		this.shitiOne6 = shitiOne6;
		this.shitiOne7 = shitiOne7;
		this.shitiOne8 = shitiOne8;
	}

	// Property accessors

	public Integer getShitiId()
	{
		return this.shitiId;
	}

	public void setShitiId(Integer shitiId)
	{
		this.shitiId = shitiId;
	}

	public String getShitiName()
	{
		return this.shitiName;
	}

	public void setShitiName(String shitiName)
	{
		this.shitiName = shitiName;
	}

	public String getShitiFujian()
	{
		return this.shitiFujian;
	}

	public void setShitiFujian(String shitiFujian)
	{
		this.shitiFujian = shitiFujian;
	}

	public String getShitiFujianleixing()
	{
		return this.shitiFujianleixing;
	}

	public void setShitiFujianleixing(String shitiFujianleixing)
	{
		this.shitiFujianleixing = shitiFujianleixing;
	}

	public String getShitiFujianyuanshiming()
	{
		return this.shitiFujianyuanshiming;
	}

	public void setShitiFujianyuanshiming(String shitiFujianyuanshiming)
	{
		this.shitiFujianyuanshiming = shitiFujianyuanshiming;
	}

	public String getShitiFaburiqi()
	{
		return this.shitiFaburiqi;
	}

	public void setShitiFaburiqi(String shitiFaburiqi)
	{
		this.shitiFaburiqi = shitiFaburiqi;
	}

	public String getShitiFabuzhe()
	{
		return this.shitiFabuzhe;
	}

	public void setShitiFabuzhe(String shitiFabuzhe)
	{
		this.shitiFabuzhe = shitiFabuzhe;
	}

	public String getShitiType()
	{
		return this.shitiType;
	}

	public void setShitiType(String shitiType)
	{
		this.shitiType = shitiType;
	}

	public String getShitiOne1()
	{
		return this.shitiOne1;
	}

	public void setShitiOne1(String shitiOne1)
	{
		this.shitiOne1 = shitiOne1;
	}

	public String getShitiOne2()
	{
		return this.shitiOne2;
	}

	public void setShitiOne2(String shitiOne2)
	{
		this.shitiOne2 = shitiOne2;
	}

	public String getShitiOne3()
	{
		return this.shitiOne3;
	}

	public void setShitiOne3(String shitiOne3)
	{
		this.shitiOne3 = shitiOne3;
	}

	public String getShitiOne4()
	{
		return this.shitiOne4;
	}

	public void setShitiOne4(String shitiOne4)
	{
		this.shitiOne4 = shitiOne4;
	}

	public Date getShitiOne5()
	{
		return this.shitiOne5;
	}

	public void setShitiOne5(Date shitiOne5)
	{
		this.shitiOne5 = shitiOne5;
	}

	public Date getShitiOne6()
	{
		return this.shitiOne6;
	}

	public void setShitiOne6(Date shitiOne6)
	{
		this.shitiOne6 = shitiOne6;
	}

	public Integer getShitiOne7()
	{
		return this.shitiOne7;
	}

	public void setShitiOne7(Integer shitiOne7)
	{
		this.shitiOne7 = shitiOne7;
	}

	public Integer getShitiOne8()
	{
		return this.shitiOne8;
	}

	public void setShitiOne8(Integer shitiOne8)
	{
		this.shitiOne8 = shitiOne8;
	}

}